"""Smoke test for OrchestratorAgent routing."""

from __future__ import annotations

import asyncio
import sys
import time
from typing import Any

import httpx

BASE_URL = "http://localhost:8000"
API = f"{BASE_URL}/api/v1"
# Long enough for planner + sub-agent, short enough so a stuck case
# doesn't block the whole suite.
DEFAULT_TIMEOUT = httpx.Timeout(60.0, connect=10.0)
ORCHESTRATOR_TIMEOUT = httpx.Timeout(45.0, connect=10.0)
INDEXING_TIMEOUT_S = 90
POLL_INTERVAL_S = 2.0

# Small astronomy paragraph — must give summarize/quiz enough signal.
SAMPLE_TEXT = """\
The Orion Nebula (M42) is a diffuse emission nebula situated south of
Orion's Belt, roughly 1,344 light years from Earth. It is the closest
region of massive star formation to our solar system and contains the
Trapezium Cluster — a tight grouping of hot O-type stars whose intense
ultraviolet radiation ionises the surrounding hydrogen, producing the
nebula's characteristic red glow. The nebula spans about 24 light years
and has an apparent magnitude of 4.0, making it visible to the naked eye
under dark skies. Stellar nurseries within M42 host hundreds of
protoplanetary discs (proplyds), some directly imaged by the Hubble
Space Telescope. The nebula is part of the larger Orion Molecular Cloud
Complex, which also contains the Horsehead Nebula and Barnard's Loop.
"""


def build_test_cases(notebook_id: str) -> list[dict[str, Any]]:
    return [
        {
            "name": "1. Meta question",
            "task_input": {"query": "What agents are available?"},
            "expected": "no useful path / empty plan",
        },
        {
            "name": "2. Summarize notebook",
            "task_input": {
                "query": "Summarize my notebook",
                "notebook_id": notebook_id,
            },
            "expected": "planner -> summarizer",
        },
        {
            "name": "3. Catalog search",
            "task_input": {"query": "Search for information about Orion Nebula"},
            "expected": "planner -> catalog",
        },
        {
            "name": "4. Quiz from notebook",
            "task_input": {
                "query": "Create a quiz about my notebook",
                "notebook_id": notebook_id,
            },
            "expected": "planner -> quiz",
        },
        {
            "name": "5. Sanity (router rule)",
            "task_input": {
                "notebook_id": notebook_id,
                "question": "What is this document about?",
            },
            "expected": "router rule -> qa (no LLM planner)",
        },
    ]


def hr(label: str = "") -> None:
    bar = "=" * 78
    if label:
        print(f"\n{bar}\n{label}\n{bar}")
    else:
        print(bar)


async def register_and_login(client: httpx.AsyncClient) -> str:
    email = f"orchtest+{int(time.time())}@example.com"
    password = "test-password-123"

    r = await client.post(
        f"{API}/users/register",
        json={"email": email, "password": password, "full_name": "Orch Test"},
    )
    if r.status_code not in (200, 201):
        raise RuntimeError(f"register failed: {r.status_code} {r.text}")
    print(f"  registered: {email}")

    r = await client.post(
        f"{API}/users/login",
        data={"username": email, "password": password},
    )
    if r.status_code != 200:
        raise RuntimeError(f"login failed: {r.status_code} {r.text}")
    token = r.json()["access_token"]
    print(f"  logged in, token: {token[:24]}...")
    return token


async def create_notebook(client: httpx.AsyncClient) -> str:
    r = await client.post(
        f"{API}/notebooks/",
        json={
            "title": "Orchestrator Test Notebook",
            "description": "Auto-generated by test_orchestrator.py",
        },
    )
    if r.status_code not in (200, 201):
        raise RuntimeError(f"create notebook failed: {r.status_code} {r.text}")
    notebook_id = r.json()["id"]
    print(f"  notebook: {notebook_id}")
    return notebook_id


async def upload_doc(client: httpx.AsyncClient, notebook_id: str) -> str:
    files = {"file": ("orion.txt", SAMPLE_TEXT.encode("utf-8"), "text/plain")}
    r = await client.post(f"{API}/notebooks/{notebook_id}/upload", files=files)
    if r.status_code not in (200, 202):
        raise RuntimeError(f"upload failed: {r.status_code} {r.text}")
    doc_id = r.json()["document_id"]
    print(f"  uploaded doc: {doc_id} (status: {r.json()['status']})")
    return doc_id


async def wait_indexed(client: httpx.AsyncClient, notebook_id: str) -> None:
    """Poll documents until all are indexed or one is failed."""
    deadline = time.monotonic() + INDEXING_TIMEOUT_S
    last_status: dict[str, str] = {}
    while time.monotonic() < deadline:
        r = await client.get(f"{API}/notebooks/{notebook_id}/documents")
        r.raise_for_status()
        docs = r.json()
        if not docs:
            await asyncio.sleep(POLL_INTERVAL_S)
            continue
        statuses = {d["document_id"]: d["status"] for d in docs}
        if statuses != last_status:
            print(f"  indexing: {statuses}")
            last_status = statuses
        if any(s == "failed" for s in statuses.values()):
            raise RuntimeError(f"document failed to index: {statuses}")
        if all(s == "indexed" for s in statuses.values()):
            return
        await asyncio.sleep(POLL_INTERVAL_S)
    raise RuntimeError(f"indexing timeout after {INDEXING_TIMEOUT_S}s")


async def run_orchestrator(
    client: httpx.AsyncClient, task_input: dict[str, Any]
) -> dict[str, Any]:
    """POST /agents/run with agent_name=orchestrator, non-streaming."""
    r = await client.post(
        f"{API}/agents/run",
        json={
            "agent_name": "orchestrator",
            "task_input": task_input,
            "stream": False,
        },
        timeout=ORCHESTRATOR_TIMEOUT,
    )
    body: dict[str, Any]
    try:
        body = r.json()
    except Exception:
        body = {"_raw": r.text}
    body["_http_status"] = r.status_code
    return body


async def list_registered_agents(client: httpx.AsyncClient) -> list[str]:
    r = await client.get(f"{API}/agents/")
    r.raise_for_status()
    return [a["name"] for a in r.json()]


def _extract_error(result: dict[str, Any]) -> Any:
    """Pull an error message from an AgentResponse or FastAPI error envelope."""
    err = result.get("error")
    if isinstance(err, dict):
        return f"{err.get('code', '?')}: {err.get('message', '')}"
    if isinstance(err, str) and err:
        return err
    detail = result.get("detail")
    if detail:
        return str(detail)
    raw = result.get("_raw")
    if raw:
        return str(raw)[:400]
    return None


def summarize_run(case: dict[str, Any], result: dict[str, Any]) -> dict[str, Any]:
    """Extract report fields from an AgentResponse."""
    http = result.get("_http_status")
    status = result.get("status")
    error = _extract_error(result)
    output = result.get("output") or {}

    step_outputs = output.get("step_outputs") if isinstance(output, dict) else None
    sub_agents: list[str] = []
    if isinstance(step_outputs, dict):
        for key in step_outputs.keys():
            parts = key.split("_", 2)
            if len(parts) == 3:
                sub_agents.append(parts[2])
            else:
                sub_agents.append(key)

    plan_summary = output.get("summary") if isinstance(output, dict) else None
    output_preview = str(output)[:200] if output else ""

    return {
        "case": case["name"],
        "expected": case["expected"],
        "http": http,
        "status": status,
        "sub_agents": sub_agents,
        "plan_summary": plan_summary,
        "error": error,
        "output_preview": output_preview,
    }


def print_case_result(report: dict[str, Any]) -> None:
    print(f"\n--- {report['case']} ---")
    print(f"  expected:     {report['expected']}")
    print(f"  http:         {report['http']}")
    print(f"  status:       {report['status']}")
    print(f"  sub-agents:   {report['sub_agents'] or '(none / empty plan)'}")
    print(f"  plan_summary: {report['plan_summary']!r}")
    if report["error"]:
        err_str = str(report["error"])
        print(f"  error:        {err_str[:400]}")
    if report["output_preview"]:
        print(f"  output:       {report['output_preview']}")


def print_final_table(reports: list[dict[str, Any]]) -> None:
    hr("SUMMARY")
    header = f"{'case':<28} {'http':<6} {'status':<11} {'sub-agents':<28}"
    print(header)
    print("-" * len(header))
    for r in reports:
        agents = ",".join(r["sub_agents"]) or "(empty)"
        print(
            f"{r['case'][:27]:<28} "
            f"{str(r['http']):<6} "
            f"{str(r['status'] or 'n/a'):<11} "
            f"{agents[:27]:<28}"
        )


async def main() -> int:
    hr("Orchestrator smoke test")
    async with httpx.AsyncClient(timeout=DEFAULT_TIMEOUT) as client:
        # Health check first — fail fast if backend isn't up.
        try:
            r = await client.get(f"{BASE_URL}/health")
            r.raise_for_status()
        except Exception as exc:
            print(f"backend not reachable at {BASE_URL}: {exc}")
            print("start it with: uvicorn main:app --reload --port 8000")
            return 2

        print("\n[1/3] auth bootstrap")
        token = await register_and_login(client)
        client.headers["Authorization"] = f"Bearer {token}"

        print("\n[2/3] notebook setup")
        notebook_id = await create_notebook(client)
        await upload_doc(client, notebook_id)
        await wait_indexed(client, notebook_id)
        print("  indexed: OK")
        agents = await list_registered_agents(client)
        print(f"  registered agents: {agents}")

        print("\n[3/3] orchestrator cases")
        cases = build_test_cases(notebook_id)
        reports: list[dict[str, Any]] = []
        for case in cases:
            t0 = time.monotonic()
            try:
                result = await run_orchestrator(client, case["task_input"])
            except Exception as exc:
                result = {
                    "_http_status": "exc",
                    "status": "failed",
                    "error": f"{type(exc).__name__}: {exc}",
                    "output": None,
                }
            dt_ms = int((time.monotonic() - t0) * 1000)
            try:
                report = summarize_run(case, result)
            except Exception as exc:
                report = {
                    "case": case["name"],
                    "expected": case["expected"],
                    "http": result.get("_http_status"),
                    "status": "report_error",
                    "sub_agents": [],
                    "plan_summary": None,
                    "error": f"summarize_run crashed: {type(exc).__name__}: {exc}",
                    "output_preview": "",
                }
            report["wall_ms"] = dt_ms
            print_case_result(report)
            print(f"  wall:         {dt_ms} ms")
            reports.append(report)

        print_final_table(reports)
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
